url: https://periodic.now.sh
title: Periodic
tagline: Command Line Utilities for the common man
description: Command Line Utilities for the common man
permalink: /:title/

markdown: redcarpet
exclude: ["sass"]
